### PR TITLE
latest src-d/ci, more ci for macOS and Windows

### PR DESCRIPTION
**Pull request by smola**
Now we run tests on:

 - Linux + Go 1.9.x
- Linux + Go 1.10.x
    
make dependencies and build (but not tests) are run on:
    
- macOS + Go 1.9.x
- macOS + Go 1.10.x
- Windows + Go 1.10.x + mingw32-make

### CODE REVIEW

**Comment by smola** [comment]
Depends on https://github.com/src-d/ci/pull/76

**Comment by dennwc** [comment]
@smola Is it okay to merge? Looks good to me.

**Comment by smola** [comment]
@dennwc The problem is that, while it works on CI, we're recommending in the `README` (as well and other dependant project README's) to run `make dependencies`. And I'm not sure how compatible is my new `make dependencies` on Windows systems that do not have exactly the same preconditions as this Appveyor.

**Comment by smola** [comment]
I think we should merge once CI passes again.

In order to avoid the error on Windows, `make clean-libuast` is called from `make dependencies` on Windows.

**Comment by dennwc** [comment]
Thanks for taking care of Windows! Highly appreciated.

**Pull request merged**
