### PR TITLE
make it compilable on mac os

### PR DESCRIPTION
**Pull request by smacker**
Fixes: https://github.com/bblfsh/client-go/issues/37

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
Please
1. Remove the warnings suppression. They are legitimate and shall be fixed in other PRs.
2. `-std=c++14` should be activated for all the platforms except `custom`. `gcc` 5+ has 11 by default and this is why we have not seen any errors yet. MacOS has `clang++` instead and it does not have this standard by default.

**Comment by smacker** [comment]
thanks! fixed.

**Comment by vmarkovtsev** [comment]
@smacker Can you please bump this so that AppVeyor build is triggered. We fixed it today.

**Comment by smacker** [comment]
done: https://ci.appveyor.com/project/mcuadros/client-go/build/2

**Comment by vmarkovtsev** [comment]
@juanjux LGTM

**Pull request merged**
