### PR TITLE
Add Windows installation instructions

### PR DESCRIPTION
**Pull request by vmarkovtsev**

### CODE REVIEW

**Comment by eiso** [comment]
Very cool!

**Comment by vmarkovtsev** [comment]
@juanjux pls do not merge, I want to add AppVeyor here

**Comment by vmarkovtsev** [comment]
This is nearly feature-complete. It depends on windows release of libuast so cannot be verified now.

**Comment by vmarkovtsev** [comment]
@juanjux It is currently hard to debug CI because `make dependencies` always succeeds - it is `.IGNORE`-ed. So either Travis or AppVeyor builds fail yet they are shown green. Shall I remove `.IGNORE`?

**Comment by vmarkovtsev** [comment]
Two tests are failing - but somehow `test-coverage` failure is ignored. I am a bit confused - I do not see it .IGNORE-ed in Makefile.main.

**Comment by juanjux** [comment]
Works now, can this be merged?

**Comment by vmarkovtsev** [comment]
It is blocked by the windows release of libuast - it downloads a zip from there. https://github.com/bblfsh/libuast/pull/71

**Comment by juanjux** [comment]
Can this be merged now?

**Comment by vmarkovtsev** [comment]
I will test the build this evening. I had few mins on lunch and it seems to be a silly error with curl certificates.

**Comment by vmarkovtsev** [comment]
@juanjux Ready to merge. My local AppVeyor build passed, I do not see it here - I guess because it is the first time.

**Comment by juanjux** [comment]
Merged and tagged (v2.2.2).

**Pull request merged**
